name: TypeScript Benchmark
on:
  pull_request:
    paths:
      - ".github/workflows/benchmark.yml"
      - "package.json"
      - "types/**"
      - "benchmarks/typescript/**"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/benchmark.yml"
      - "package.json"
      - "types/**"
      - "benchmarks/typescript/**"
permissions:
  contents: read

jobs:
  typescript:
    runs-on: ubuntu-22.04
    name: Benchmark TypeScript Types
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 16

      - run: npm install

      - run: node ./scripts/create-tarball.js

      - run: npm run ts-benchmark
