on:
  push:
    branches: ['main']
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  id-token: write

name: encryption-tests

jobs:
  set-up:
    permissions:
      # required for all workflows
      security-events: write
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Install mongodb-client-encryption
        uses: mongodb-client-encryption

      - name: Set-up cluster
      - shell: bash

  run-tests:
    needs:
      - set-up
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [20]
        os: [ubuntu-latest]
        mongodb: [8.0.0]
    #clone drivers-evergreen-tools (will delete itself once the run is over)
    git clone --depth=1 https://github.com/mongodb-labs/drivers-evergreen-tools.git /data/mci/ead9f9a67ef900991e09bd9589dfee0e/drivers-tools
    #set path 
    #calling run orchestration sets up a server on your computer
    # it outputs relevants uri in expansions.yml
    # put uri into an environment variable
    - name: set-up-orchestration
    - command: subprocess.exec
      params:
        binary: bash
        add_expansions_to_env: true
        env:
          # The following is the settings for how we want to launch mongodb
          MONGODB_VERSION: ${VERSION}
          TOPOLOGY: ${TOPOLOGY}
          AUTH: ${AUTH}
          SSL: ${SSL}
          ORCHESTRATION_FILE: ${ORCHESTRATION_FILE}
          REQUIRE_API_VERSION: ${REQUIRE_API_VERSION}
          LOAD_BALANCER: ${LOAD_BALANCER}
          COMPRESSOR: ${COMPRESSOR}
          # These are paths necessary for launching mongodb
          DRIVERS_TOOLS: ${DRIVERS_TOOLS}
          MONGODB_BINARIES: ${MONGODB_BINARIES}
        args:
          - .github/scripts/run-orchestration.sh
    name: Encryption tests
    env:
      FORCE_COLOR: true
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Setup node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: latest
      - name: Load MongoDB binary cache
        id: cache-mongodb-binaries
        uses: actions/cache@v4
        with:
          path: ~/.cache/mongodb-binaries
          key: ${{ matrix.os }}-${{ matrix.mongodb }}
      - name: Install Dependencies
        run: npm install
      - name: Install drivers-evergreen-tools
      
      - name: Test
        run: mocha --exit ./test/encryption/*.test.js