name: Typescript Types
on:
  pull_request:
    paths:
      - '.github/workflows/tsd.yml'
      - 'package.json'
      - 'types/**'
      - 'test/types/**'
  push:
    branches:
      - master
    paths:
      - '.github/workflows/tsd.yml'
      - 'package.json'
      - 'types/**'
      - 'test/types/**'
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint TS-Files
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 20

      - run: npm install

      - name: Lint TS-Files
        run: npm run lint-ts

  test-ts-types:
    needs:
      - lint
    runs-on: ubuntu-latest
    name: Test Typescript Types
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Setup node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 20

      - run: npm install

      - name: Typings
        run: npm run test-tsd
